FROM centos:7.4.1708

RUN yum install -y wget && wget http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm && rpm -ivh epel-release-7-11.noarch.rpm && \
    yum install -y jemalloc logrotate

RUN wget http://www.rpmfind.net/linux/epel/7/x86_64/Packages/r/redis-3.2.12-2.el7.x86_64.rpm && rpm -ivh redis-3.2.12-2.el7.x86_64.rpm


RUN sed -i "s/bind 127.0.0.1/bind 0.0.0.0/g"  /etc/redis.conf

RUN systemctl enable redis

VOLUME /var/lib/redis
# WORKDIR /data

# ENTRYPOINT ["/usr/sbin/init"]

EXPOSE 6379

# CMD [ "systemctl restart redis" ]
CMD ["/usr/sbin/init"]

# docker build -t my_redis:3.2.12 -f Dockerfile .
# docker run -d --privileged -p 6379:6379 -v $PWD/redis_data:/var/lib/redis my_redis:3.2.12